
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/miro/anaconda3/lib/python3.12/site-packages/cmake/data/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:1 (project)"
    message: |
      The system is: Linux - 6.8.0-48-generic - x86_64
...
